spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/shop_manage_db
    username: shopManageAdmin
    password: testpassword

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

file:
  upload:
    path: /home/silmoon/MyProjects/Java/shopmanagement/src/main/resources/static/goodsimg

server:
  port: 8181